"""D122 ResponseRewriteDetection -- detect post-generation content injection.

Sends a request asking for a specific exact marker. Checks if the response
contains that marker AND whether extra rewrite indicators (branding,
disclaimers) have been appended by the router.
"""
from __future__ import annotations

from ..models import (
    DetectorResult,
    JudgeMode,
    Priority,
    ProbeRequest,
    ProbeResponse,
)
from ..registry import BaseDetector, detector

_MARKER = "EXACT_OUTPUT_MARKER_7X9Q"

_REWRITE_INDICATORS = [
    "powered by",
    "disclaimer:",
    "generated by",
    "brought to you",
    "sponsored",
    "\u00a9",
    "all rights reserved",
]


@detector
class D122_ResponseRewriteDetection(BaseDetector):
    detector_id = "D122"
    detector_name = "ResponseRewriteDetection"
    priority = Priority.P1
    judge_mode = JudgeMode.ONCE
    request_count = 1
    description = "Detect post-generation content rewriting or branding injection"

    async def send_probes(self) -> list[ProbeResponse]:
        return [await self.client.send(ProbeRequest(
            payload={
                "model": self.config.claimed_model,
                "temperature": 0,
                "max_tokens": 20,
                "messages": [{"role": "user", "content": (
                    f"Reply with ONLY the text: {_MARKER}"
                )}],
            },
            endpoint_path=self.config.default_endpoint_path,
            description="D122 rewrite detection probe",
        ))]

    def judge(self, responses: list[ProbeResponse]) -> DetectorResult:
        r = responses[0]
        if r.is_network_error:
            return self._inconclusive(r.error or "network error")
        if r.status_code != 200:
            return self._inconclusive(r.error_detail)

        content = r.content
        if not content:
            return self._inconclusive("empty content")

        has_marker = _MARKER in content
        # Only check for rewrite indicators AFTER the marker position.
        # Models may prepend natural text before the marker; we only care
        # about router-injected content appended after the expected output.
        marker_end = content.find(_MARKER)
        if marker_end >= 0:
            marker_end += len(_MARKER)
        else:
            marker_end = 0
        after_marker = content[marker_end:].lower()
        found_indicators = [
            ind for ind in _REWRITE_INDICATORS if ind in after_marker
        ]

        evidence = {
            "has_marker": has_marker,
            "content_preview": content[:150],
            "rewrite_indicators": found_indicators,
        }

        if not has_marker:
            # Model may simply not follow "reply with ONLY this marker"
            # instructions. Only FAIL if rewrite indicators are also present
            # (clear evidence of router appending content). Otherwise PASS —
            # no evidence of router manipulation.
            if found_indicators:
                return self._fail(
                    f"marker missing AND rewrite indicators found: "
                    f"{', '.join(found_indicators)}",
                    evidence,
                )
            return self._pass(evidence | {
                "note": "marker not echoed but no rewrite indicators detected",
            })
        if found_indicators:
            return self._fail(
                f"rewrite indicators found after marker: {', '.join(found_indicators)}",
                evidence,
            )
        return self._pass(evidence)

    @classmethod
    def _test_cases(cls):
        def _resp(content: str) -> ProbeResponse:
            return ProbeResponse(
                status_code=200,
                body={"choices": [{"message": {"role": "assistant", "content": content}, "finish_reason": "stop"}]},
            )

        return [
            ("PASS: exact marker only",
             [_resp(_MARKER)], "pass"),
            ("PASS: marker missing but no rewrite indicators",
             [_resp("Hello there!")], "pass"),
            ("FAIL: marker present but with branding",
             [_resp(f"{_MARKER}\n\nPowered by SuperAI Gateway. All rights reserved.")], "fail"),
            ("INCONCLUSIVE: empty content",
             [_resp("")], "inconclusive"),
            ("INCONCLUSIVE: network error",
             [ProbeResponse(status_code=0, error="TIMEOUT")], "inconclusive"),
        ]


if __name__ == "__main__":
    D122_ResponseRewriteDetection.self_test()
